### ISSUE TITLE
Namespace and global function conflict

### ISSUE THREAD

**Issue by ghost** [hyperoslo/Whisper#100]
Hi,

I have a name conflict with my model class "Message".
Tried to use Whisper's struct "Message" like `Whisper.Message` but it conflicts with global function 
`Whisper(message: Message, to: UINavigationController, action: WhisperAction = .Show)`

Best regards and thanks for the lib :)

**Comment by ghost** [comment]
I found "workaround" for this issue.

```
protocol Messegeable {

    var title: String { get set }
    var backgroundColor: UIColor { get set }
    init(title: String, backgroundColor: UIColor)
}



extension Whisper.Message: Messegeable {

    init(title: String, backgroundColor: UIColor) {
        self.title = title
        self.backgroundColor = backgroundColor
        self.textColor = UIColor.blackColor()
        self.images = nil
    }
}



struct WhisperHelper {

    static func createNotifierMessage<T: Messegeable>(title: String, backgroundColor: UIColor) -> T {
        return T.init(title: title, backgroundColor: backgroundColor)
    }
}
```

And now, to create Whisper's Message:

`let message: Whisper.Message = WhisperHelper.createNotifierMessage("custom title", backgroundColor: UIColor.grayColor())`

**Comment by onmyway133** [comment]
@Filozoff Hi, as of release 3.1.0, we rename global functions, so you only need to remember `show` and `hide`, and the `Whisper` namespace is reserved 🎉
