### ISSUE TITLE
Shout duration?

### ISSUE THREAD

**Issue by Gob-Lin** [hyperoslo/Whisper#113]
Hello,
is it possible to set the duration of a Shout?
Even better, make it permanent and dismissable tapping on it?

Thanks,

P

**Comment by RamonGilabert** [comment]
Yes! A `shout` needs an `announcement` to work. Such `announcement` has a duration property when creating it that defaults to 2.

Here it is: https://github.com/hyperoslo/Whisper/blob/master/Source/Message.swift#L26. :)
