### ISSUE TITLE
Showing.swift file doesn't download on pod install

### ISSUE THREAD

**Issue by fergonzalez** [hyperoslo/Whisper#115]
I can't find the Showing.swift file after install the pod.

Thanks!

**Comment by onmyway133** [comment]
@fergonzalez Hi, how do you declare `Whisper` in your Podfile? And how is `Whisper` shown up in  your Podfile.lock?

**Comment by fergonzalez** [comment]
Hi 
`pod 'Whisper'` 
just like the Readme

and in my pod file.lock:
- Whisper (3.0.0)

**Comment by onmyway133** [comment]
@fergonzalez Hi, can you do `pod update Whisper`. Version `3.1.1` should work fine

**Comment by fergonzalez** [comment]
It works! Thanks @onmyway133!!!

**Comment by onmyway133** [comment]
@fergonzalez 🎉 Closing it for now. Feel free to reopen it
