### ISSUE TITLE
'show' is getting confused with UIViewController show in swift3 branch

### ISSUE THREAD

**Issue by bedaronco** [hyperoslo/Whisper#116]
The latest beta XCode is having issues with the show method.  There is a show method on UIViewController that it keeps getting confused with.  Not sure why it can't differentiate between the two but it can't.

A better way of defining these methods might be the following:

`public func showAnnouncement(_ announcement: Announcement, to: UIViewController, completion: (() -> Void)? = nil)`

`public func showMurmur(_ murmur: Murmur, action: WhistleAction = .show(1.5))`

`public func showMessage(_ message: Message, to: UINavigationController, action: WhisperAction = .Show)`

Then you can leave the first label off when calling:

`showAnnouncement(announcementVar, to: self)`
`showMurmur(murmurVar, .show(2.0))`
`showMessage(messageVar, to: self.navigationController, .Show(2.0))`

**Comment by onmyway133** [comment]
@bedaronco Hi, can you use namespace to avoid conflict, like `Whisper.show`?

**Comment by bedaronco** [comment]
Yes, that would work too.

**Comment by RamonGilabert** [comment]
Hey @bedaronco, thanks for your issue! I think using the namespace is a much more Swifty way than actually putting the whole description of what you want to accomplish (it's more an Objective C thing I guess).

Closing the issue. Feel free to reopen it if you have any questions!

**Comment by bedaronco** [comment]
Yes, that works, thanks!

Have you ever thought about renaming the structs?  There's still something that doesn't quite flow with the current implementation.  For instance, why not call the structs what they're referred to in the documentation and the show methods?  So instead of Message, Announcement, and Murmur, why not Whisper, Shout, and Whistle?  The API is a bit confusing when you have to create a Murmur but then refer to it as a whistle: 

`Whisper.show(whistle: murmur)`

Wouldn't it be better if you could create a Whistle and pass that to show?

Just a suggestion.

**Comment by RamonGilabert** [comment]
I like that. What do you think about it, @hyperoslo/ios?

**Comment by zenangst** [comment]
I like this suggestion!

**Comment by LucidityDesign** [comment]
Is this already implemented? Isn't `Whisper` undefined?

**Comment by onmyway133** [comment]
@LucidityDesign Hi, `Whisper` is the name of this framework, so Swift makes that a namespace as well. Have you tried that? What is the error you get?

**Comment by LucidityDesign** [comment]
I think it was another problem, but thanks for your help

**Comment by MichaelBressler** [comment]
let's make this open or something so other people can see it better. I spent 3 hours scouring google and the web trying to figure it out. Thanks!

**Comment by onmyway133** [comment]
@MichaelBressler Hi, you have the this namespace issue, too?

**Comment by MichaelBressler** [comment]
Yes.  It was very frustrating.

I tried breaking the pod - changing the name of the method - which is a poor solution.

I'm new to swift and didn't realize how to modify scope and was confused by the autocompletes and the compilers being in conflict.

**Comment by LucidityDesign** [comment]
Maybe you can add a section "known issues" to the readme
