### ISSUE TITLE
Misplaced KVNProgress alert when a murmur is shown

### ISSUE THREAD

**Issue by waydevin** [hyperoslo/Whisper#125]
[KNVProgress](https://github.com/AssistoLab/KVNProgress) alert would be misplaced at the very top beyond the screen bounds when there's a `murmur` shown at the status bar position.

Please refer to [issue95](https://github.com/AssistoLab/KVNProgress/issues/95) at KVNProgress page.

Many thanks to this awesome library!

**Comment by RamonGilabert** [comment]
Let's take it there to have it just in one place. 😊
