### ISSUE TITLE
Can't get Shout to work in Swift 3

### ISSUE THREAD

**Issue by ghost** [hyperoslo/Whisper#126]
Hi there,

I am really struggling with implementing the Shout in my app, and I have tried to follow the instructions regarding code, as well as trying several other methods in an attempt to make it work.

Here is two attempts I've tried:

```
        let anno = Announcement(title: "My title", subtitle: "My subtitle", image: UIImage(named: ""), duration: 3.0) { 

            show(shout: anno, to: ViewController)

        }
```

And:

```
        let anno = Announcement(title: "My title", subtitle: "My subtitle", image: UIImage(named: ""), duration: 3.0, action: nil)

        show(shout: anno, to: ViewController)
```

I have also tried to switch between using 'ViewController' and 'self' with no luck. Any ideas on how I would implement this correctly? 

Thanks in advance!

**Comment by srmds** [comment]
@askaale Try the following, which is working in Swift 3:

```
import Whisper

let anno = Announcement(title: "My title", 
                        subtitle: "My subtitle",
                        image: UIImage(named: ""),
                        duration: 3.0) 

Whisper.show(shout: anno, to: self)
```

Note: `self` can be any viewcontroller.
