### ISSUE TITLE
Shout like a murmur.

### ISSUE THREAD

**Issue by waydevin** [hyperoslo/Whisper#127]
Hi,
I am trying to make a shout when there's a remote notification gets received.
The problem is that I can't make sure which controller would be presented at the moment, thus I hope to make the shout visible like a murmur is at the top layer above any controllers.
Is it possible to make a shout act like that?

**Comment by Alex293** [comment]
Same here any solutions ?

**Comment by LordOfTheRains** [comment]
will something like this work for you guys?            

            guard let topVCWindow = UIApplication.shared.keyWindow else{
                return
            }
            guard let currentVC = topVCWindow.currentViewController() else{
                return
            }
            Whisper.show(shout: announcement, to: currentVC)
