### ISSUE TITLE
Swift 3 brokeness

### ISSUE THREAD

**Issue by adamdahan** [hyperoslo/Whisper#131]

**Comment by RamonGilabert** [comment]
?

**Comment by adamdahan** [comment]
Oh sorry I didn't post the comment. The library is broken in Swift 3. Basically signatures for methods show etc.. don't pass dynamic compilation in Xcode 8.

**Comment by onmyway133** [comment]
@adamdahan Hi, this may relate to https://github.com/hyperoslo/Whisper/issues/116
If that is the case, you need to use namespace like `Whisper.show(...)`

**Comment by pathawee** [comment]
![screen shot 2559-11-23 at 10 51 19 am](https://cloud.githubusercontent.com/assets/5134572/20550689/dc3d7ed6-b16a-11e6-9459-bab7ab046389.png)

Just install to new project and run build (not implement yet)

**Comment by onmyway133** [comment]
@pathawee can I check with you what is `Whisper` version in your `Podfile.lock`?

**Comment by pathawee** [comment]
@onmyway133 
  - Whisper (3.1.1)

**Comment by onmyway133** [comment]
@pathawee Hi, have you checked the `Release` tab in Github? The version that supports Swift 3 is https://github.com/hyperoslo/Whisper/releases/tag/4.0.0
