### ISSUE TITLE
'Message' is ambiguous without more context

### ISSUE THREAD

**Issue by Laptopmini** [hyperoslo/Whisper#133]
I am currently running into the problem (after migrating to Swift 3), where the `Whisper.Message` class is conflicting with another library I use, lets call it, `MyLibrary.Message`.

When I write the following line:
```
let message: Whisper.Message = Whisper.Message(title: messageValue, textColor: .whiteColor(), backgroundColor: FAILURE_RED)
```

I get an "ambiguous context" error. However, I completely out of ideas on how to make the context clearer here. Any ideas?

**Comment by RamonGilabert** [comment]
Hey @Laptopmini,

Can you try to delete `Whisper.Message` as the type?

And also, is it `.whiteColor()` in Swift 3? I seem to recall it's just `.white`.

**Comment by Laptopmini** [comment]
Heyyyyyyy, that worked!

Thanks, I was starting to pull my hair out. :)
