### ISSUE TITLE
Feature: ability to change current message

### ISSUE THREAD

**Issue by nineboxes** [hyperoslo/Whisper#134]
Need ability to change current message (title, backgroundColor, titleColor) with different animation and maybe with some predefined images (on the left or right side of the text) like check mark (for example, see internet connection of slack for ios).
Thanks!

**Comment by RamonGilabert** [comment]
Why don't you present another Whisper instead?

**Comment by nineboxes** [comment]
@RamonGilabert simply, it's not what i want :) 
and for now i've already implemented some manipulation with current whisper, but code looks pretty ugly. so, will be nice if you provide some api for this sort of things.

**Comment by RamonGilabert** [comment]
Feel free to make a PR with your changes. Then we can review it and improve it.
