### ISSUE TITLE
Notification will stuck on screen without any response

### ISSUE THREAD

**Issue by aterite** [hyperoslo/Whisper#139]
It's hard to reproduce, but if you drag notification at wrong time it will stuck on screen and gesture recognizers wont work. It goes away only if next notification is presented.
I'm using this to show announcement with action and duration=4.
public func show(shout announcement: Announcement, to: UIViewController, completion: (() -> Void)? = nil)

**Comment by yarodevuci** [comment]
@aterite Same thing happens to me as well
@hyper-jenkins-bot @JohnSundell Are you able to fix that?

**Comment by yarodevuci** [comment]
Was it fixed?

**Comment by 3lvis** [comment]
Hey @yarodevuci! I'm trying to take over the project and had to clean up old issues to reduce the noise. If you are able to reproduce it in the latest version I'll be happy to take a look. :)
