### ISSUE TITLE
Please change your show(whistle, action) method because it conflicts with show(viewController: completion) of UIViewController

### ISSUE THREAD

**Issue by peihsendoyle** [hyperoslo/Whisper#144]
Like the title I said, please change the method name. Thanks :)

**Comment by onmyway133** [comment]
@peihsendoyle Hi, it seems similar to https://github.com/hyperoslo/Whisper/issues/116. Have you tried `Whisper.show(...)`?

**Comment by gali8** [comment]
Use:
**Whisper.show**(shout: msg, to: self.navigationController!)
**Whisper.show**(whisper: msg, to: self)
**Whisper.show**(whistle: msg, to: self.navigationController!)
**Whisper.show**(whistle: Murmur(title: "the message"), action: WhistleAction.present)
etc...

**Comment by onmyway133** [comment]
@gali8 Hi thanks. You're right, that is the way to use it in case of method conflict. I will close this for now
