### ISSUE TITLE
Whisper.show bug

### ISSUE THREAD

**Issue by cwt2829** [hyperoslo/Whisper#148]
the setup is like this:
when u click button A, it call Whisper.show 

If u click multiple time on that buttonA, ur screen will keep pushed up and it getting smaller

**Comment by cammyc** [comment]
I've had this problem too, specifically with tableviews. Half the time a whisper is shown it slides the entire view up with it, underneath the nav bar, as it disappears.

**Comment by farice** [comment]
Any word on how to fix this bug?

**Comment by cwt2829** [comment]
I end up using this library 
https://github.com/SwiftKickMobile/SwiftMessages

**Comment by benguild** [comment]
Related: https://github.com/hyperoslo/Whisper/issues/70

**Comment by pushchris** [comment]
Experiencing this issue as well. Showing a Whisper on top of another Whisper then hiding one of them makes the entire screen move upward. Can reproduce quite easily.
