### ISSUE TITLE
Incorrect Argument Labels in Call

### ISSUE THREAD

**Issue by tylermrolfe** [hyperoslo/Whisper#149]
So I've copied the demo code directly from the readme
`let murmur = Murmur(title: "This is a small whistle...")`
`show(whistle: murmur, action: .show(0.5))`

Xcode is then giving me an error saying "Incorrect argument labels in call (have 'whistle:action:'. expected '_:sender')"

Xcode then gives me a fixit to change it to
 `let murmur = Murmur(title: "This is a small whistle...")
  show(murmur, sender: .show(0.5))`

Then the error becomes, "Cannot convert value type 'Murmur' to expected argument type 'UIViewController'."

Any idea what's going on here?

Installed via Carthage
Xcode v8.2.1
Swift 3

**Comment by onmyway133** [comment]
@tylermrolfe Hi, sorry for the confusion. It is because UIViewController also has `show` method, we will update the README https://github.com/hyperoslo/Whisper/pull/150
