### ISSUE TITLE
How Whisper can be installed manually (without cocoapods etc)?

### ISSUE THREAD

**Issue by moonvader** [hyperoslo/Whisper#154]
I just added Source folder of this repo to my Xcode project and added code 

let murmur = Murmur(title: "This is a small whistle...")

// Show and hide a message after delay
Whisper.show(whistle: murmur, action: .show(0.5))

what else should i do?

**Comment by onmyway133** [comment]
@moonvader Hi, thanks for using `Whisper`, does it work for you after adding the code? What problem do you have? `Whisper` relies only on `UIKit` so if you use it from an iOS project, you don't need to do anything else. But the `show` method may conflict with `UIViewController 's show` method, you probably need to rename those
