### ISSUE TITLE
What if I don't have a UINavigationController?

### ISSUE THREAD

**Issue by superandrew** [hyperoslo/Whisper#157]
Hello, I searched the docs before asking this question, to no avail.

I have a tabbed application which is using [MHCustomBarController](https://github.com/hartlco/MHCustomTabBarController)

Unfortunately, this pattern has no navigationController at the `appDelegate.window.rootViewController` level.

So how am I able - if it is possible at all - to show a shout from a regular viewController? I even tried to embed my initialViewController into a UINavigationController, but it is always `nil`, probably because the `appDelegate.window.rootViewController` could not have a `UINavigationController`.

My use case is to have a centralized function in appDelegate that notifies regardless from the tab I'm in currently.

Is it a design limitation? Any idea is appreciated.

**Comment by satishVekariya** [comment]
I think embed tabBar controller in to UINavigationController

**Comment by viktorasl** [comment]
Why does `public func show(shout announcement: Announcement, to: UIViewController, completion: (() -> Void)? = nil)` not work for your case?
