### ISSUE TITLE
NavigationController Hide Announcement 

### ISSUE THREAD

**Issue by syedrazackimran** [hyperoslo/Whisper#162]
Hi 

I try to implement your lib. but i don't know how to resolve my problem . i try to show some Announcement on viewdidload .  

 let _announcement = Announcement(title: "title", subtitle: "subTitle", image: UIImage.init(named: "AppIcon40x40"), duration: 3) {
             print("action clicked!")
            Whisper.hide()
 }
   Whisper.hide(whisperFrom: self.navigationController!)
        Whisper.show(shout: _announcement, to: self, completion: {
            print("The shout was silent.")
 })

its work's fine . but that announcement show behind of navigaionbar .. i need to show in front of navigation bar . kindly help me. thanks in advance . here i add screenshot kindly check it
![simulator screen shot jun 12 2017 12 48 08 pm](https://user-images.githubusercontent.com/15051045/27020762-08fbb50e-4f6e-11e7-89ac-d99c5cd2a987.png)

**Comment by viktorasl** [comment]
Hi. I assume there is a problem that you're showing shout in view controller
`Whisper.show(shout: _announcement, to: self, completion: {`
because `self` is `UIViewController`. You need to do:
`Whisper.show(shout: _announcement, to: navigationController!, completion: {`
