### ISSUE TITLE
Whisper does not resize on iPad screen

### ISSUE THREAD

**Issue by haithngn** [hyperoslo/Whisper#163]
![screen shot 2017-06-20 at 3 29 29 pm](https://user-images.githubusercontent.com/22902671/27323898-6d415fc2-55cd-11e7-8ecb-5741562f72c5.png)

It's seem Whisper bar does not auto resize on the ipad screen ?

**Comment by luketehira** [comment]
It looks like there is a pull request to address this that hasn't been merged yet. (I was just about to log the same issue). 

What did you end up doing?
