### ISSUE TITLE
Split status bar support for iOS 11...?

### ISSUE THREAD

**Issue by benguild** [hyperoslo/Whisper#167]
Hi, part of my renewed interest in this library is from what's coming up with the next iPhone, etc.

It's early to say for sure what's going to be revealed from Apple's side of things, but is there any discussion currently regarding features being deprecated or replaced given the split status bar on rumored devices?

**Comment by jondwillis** [comment]
As a temporary solution, I have modified the library to put `whistle(murmer:)`s at the bottom of of the screen, at about double the normal height, if on iPhone X. You can use screen size for detecting iPhone X for now.

This could be sort of taken as a hint that this UI paradigm should not be used.
