### ISSUE TITLE
[design issue] Doesn't support simultaneous multiple view controller display

### ISSUE THREAD

**Issue by benguild** [hyperoslo/Whisper#168]
There's an issue with this.
Because it's designed as a singleton, it'll only display on a single view controller at once.

So, if you want to display on a view controller that's presenting another view controller in case someone presses "Cancel" and goes back to it without missing the message, this does not work.

**Comment by benguild** [comment]
I don't see the reason that this needs to be kept alive as a singleton. It seems like if you call...
```swift
WhisperFactory.init().craft()
```

... It works the same as:
```swift
whisperFactory.craft()
```

... is there a particular behavior here that's being retained in a single instance that will break otherwise?

**Comment by benguild** [comment]
It seems like if you have `modifyInsets` turned off (which is more stable anyway) it doesn't really matter...?

**Comment by peihsendoyle** [comment]
It's very important case. In my opinion, it should be merged to current version.
