### ISSUE TITLE
How to manually install Whisper just by drag source code?

### ISSUE THREAD

**Issue by peihsendoyle** [hyperoslo/Whisper#171]
As I mentioned on the title, I want to work with Whisper just by manually drag it to my project. I am a person that don't like CocoaPods, Carthage or any else dependency manager. In my opinion, it make slow project build time and hard to be edited without pull requests. Manually dragging Whisper source code to project, I could customize it also.

Unfortunately, Whisper somehow create files via a module map (or something else) so that when I drag "Sources" folder to project and build, the Xcode said that it can't find the file named Whisper.

Please update the "Manually installation via drag and drop". I think many developers will love it.

Thanks much for your contribution on Whisper.

**Comment by Roninito** [comment]
I second this request. Manual installation would make this more widely usable.

**Comment by onmyway133** [comment]
@peihsendoyle @Roninito Hi, you can just drag the source files you want to use. `Whisper` does not use any module map, and there's no file named `Whisper.swift` if you take a look at the source folder https://github.com/hyperoslo/Whisper/tree/master/Source

Also, note that you need to solve any conflicts yourselves as there is no namespace `Whisper`, for example there is a `show` function that could conflict with `UIViewController` 's `show` method
