### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by Blackjacx** [hyperoslo/Whisper#172]
Will you support Swift 4?

**Comment by onmyway133** [comment]
@Blackjacx Hi, we're in the process of converting out projects to Swift 4. There are many projects so it will take time. Will keep you posted

**Comment by barnaclejive** [comment]
I've forked the project and made the updates for my own use until @onmyway133 can make the official updates. I did submit a PR if that helps at all. For now I'll point my podfile at my own repo
pod 'Whisper', :git => 'https://github.com/barnaclejive/Whisper', :branch => 'master'

**Comment by onmyway133** [comment]
@Blackjacx Hi, we're in the process of migrating Whisper to swift 4, you can see the status here https://github.com/hyperoslo/Whisper/tree/swift4. Feel free to comments or review 😉

**Comment by Blackjacx** [comment]
Think this should remain open until the release is out ;)

**Comment by akabab** [comment]
is release 5.0.1 supposed to do the job? cause I still have issue, especially I have the @objc stuffs missing. I have to set pod to SWIFT_VERSION 3.2 to make it through

**Comment by onmyway133** [comment]
@akabab Hi, can I see your Podfile.lock? Can you run the demo project ?

**Comment by onmyway133** [comment]
@Blackjacx @akabab Hi, you can check https://github.com/hyperoslo/Whisper/releases/tag/6.0.0

**Comment by akabab** [comment]
@Blackjacx thx
