### ISSUE TITLE
iOS 11 & iPhone X

### ISSUE THREAD

**Issue by Droppix** [hyperoslo/Whisper#173]
Don't work with iOS 11 and iPhone X.
New release ?

**Comment by AndrewGable** [comment]
I agree, we are having issues with this on the iPhone X simulator. Here is one example of when we show a`Murmur`

![30352968-132948fe-97d8-11e7-9e8c-e41d7348d346](https://user-images.githubusercontent.com/2838819/30838581-3d243184-a221-11e7-874b-5e7c11f35192.png)

Do you have any ides on how to fix this?

**Comment by onmyway133** [comment]
@Droppix @AndrewGable Hi, this is known issue. We 'll try to fix this during the swift 4 migration

**Comment by AndrewGable** [comment]
Awesome, is the proposed fix to extend the `Murmur` completley bellow the notch?

**Comment by derikflanary** [comment]
May I ask when the Swift 4 migration is expected to be completed?

**Comment by FraDeliro** [comment]
I have made a pull request with the update of this issue, you can check it. Thanks

**Comment by wowlocal** [comment]
Hey guys, i fix this here https://github.com/hyperoslo/Whisper/pull/179

**Comment by zenangst** [comment]
Hey folks, I just merged #179 into `master`. This seems to do the trick when I tested, please confirm that it works for you guys :) I also med #183 to reduce some code-duplication, that will be merged shortly.

**Comment by zenangst** [comment]
@derikflanary I think when #183 is merged we can make a new `5.x` version and then merge one of the `swift4` PR's and make a `6.x` release.

**Comment by magonicolas** [comment]
on an iPhone X I have a StatusBarNotificationBanner that looks way to height, this will be solved? Or how can I decrease the hight myself? [Image](https://www.dropbox.com/s/qbeqtl4bjy28m8u/Screen%20Shot%202017-10-23%20at%203.16.58%20PM.png?dl=0)

**Comment by onmyway133** [comment]
@Droppix @wowlocal @derikflanary Hi, you can check https://github.com/hyperoslo/Whisper/releases/tag/6.0.0. This is mostly language update, and small fixes to make it look nice on iPhone X. There's some other issues and PRs that we will try to deal with soon

**Comment by barnaclejive** [comment]
Was this tested on non-iPhone X? I just pulled tag 6.0.0 and ran it on an iPhone 8 Simulator and the Murmur will drop down below the status bar. I assume this is how it has to work on iPhone X, but on other devices it should still just drop into the status bar area, not below it.

![simulator_screen_shot_-_iphone_8_-_2017-10-31_at_12_16_52](https://user-images.githubusercontent.com/5251331/32238486-e46ce7bc-be35-11e7-903f-c0b96bb25ce0.png)

**Comment by jondwillis** [comment]
@barnaclejive 

<img width="545" alt="screen shot 2017-11-04 at 2 11 47 pm" src="https://user-images.githubusercontent.com/906671/32409501-27ad118c-c16a-11e7-89dc-1ea0584f0e9a.png">


I have implemented `Whistle`s in my own branch such that they **appear under the status bar on iPhone X**, but extend all the way to the top of the screen. Additionally, I have also preserved the behavior where they **appear over the status bar on other devices.**

See commit: https://github.com/jondwillis/Whisper/commit/afcd4713b4d4e185a30bcbf321f7357c7000facf

Someone should disentangle and clean up my fork and do a pull request if they wish to see this behavior in the mainline. In my application, `safeAreaInsets` do not change, but to be production-ready, the final version of this should observe `safeAreaInsetsDidChange`


Though I subjectively like extending from the top edge on iPhone X, doing this may be against Apple's guidelines, and may result in a App Store review rejection. I have noticed that snapchat changed its Whistle-like implementation on iPhone X to look kind of like a push notification does; it is below the status bar, and does not touch any edges.

`Shout`s/`Announcement`s also need to be fixed for iPhone X and AFAIK that hasn't been done.

For reference here is what Snapchat is doing:

![img_0029](https://user-images.githubusercontent.com/906671/32409864-a2fce838-c171-11e7-820d-11a73b2e8ee4.jpg)

**Comment by jondwillis** [comment]
Update: I was able to publish an app with this Whistle behavior to the App Store. So, anecdotally, it is acceptable under Apple's Guidelines.

**Comment by onmyway133** [comment]
@barnaclejive Hi, can you check https://github.com/hyperoslo/Whisper/releases/tag/6.0.2 which merged https://github.com/hyperoslo/Whisper/pull/193
@jondwillis We will go with full notch extend for now 👍 
I will close this in favor of https://github.com/hyperoslo/Whisper/issues/188
