### ISSUE TITLE
Whistle broken

### ISSUE THREAD

**Issue by johnnyoin** [hyperoslo/Whisper#188]
Version 5.1.0 broke the whistle layout as shown in this demo screenshot
![whistle screenshot](https://user-images.githubusercontent.com/3419969/31822148-fa120f20-b5a7-11e7-9950-31a72bc9604e.png)

**Comment by akabab** [comment]
Having the same issue, any update?

**Comment by StarWars** [comment]
Same here.  Here is the code to recreate:
```
                self.activeMurmur = Murmur(title: "murmur".localized)
                self.activeMurmur.backgroundColor = UIColor.red
                self.activeMurmur.titleColor = UIColor.white
                Whisper.show(whistle: self.activeMurmur, action: .present)
```

**Comment by matt-lebl** [comment]
I am also having this issue. Very frustrating 😕

**Comment by jondwillis** [comment]
This is related to iPhone X support. See my comment in https://github.com/hyperoslo/Whisper/issues/173

**Comment by onmyway133** [comment]
@johnnyoin @akabab @blerchy @jondwillis @StarWars Hi, can you check https://github.com/hyperoslo/Whisper/releases/tag/6.0.2 which merged https://github.com/hyperoslo/Whisper/pull/193
