### ISSUE TITLE
UITextField loses focus when a Whisper is called

### ISSUE THREAD

**Issue by martinschilliger** [hyperoslo/Whisper#189]
I have a UITextField whose text gets validated while the user inputs coordinates for a map. I've wanted to show an error message for misspelled coordinates with Whisper:
````
let msg = Entered %@ coordinates"
let murmur = Murmur(title: msg)
Whisper.show(whistle: murmur, action: .show(2.5))
````

My problem is, that each time a Whisper gets displayed the UITextField loses focus. Does anyone have an idea where this is triggered so that it could be prevented?

Thank you for your help!

**Comment by FreudGit** [comment]
Same problem here, i'll be happy to get a hint. :)

**Comment by martinschilliger** [comment]
Bug got fixed by @jondwillis, thank you!
https://github.com/hyperoslo/Whisper/pull/186
