### ISSUE TITLE
Use of unresolved identifier 'safeAreaInsets'

### ISSUE THREAD

**Issue by omidgolparvar** [hyperoslo/Whisper#192]
Hi,
I install Whisper via pod, and Cocoapod installed `Whisper (5.1.0)`. But when I build my project, it fails because of error: 

`/Users/Golparvar/.../Pods/Whisper/Source/UIView+Extensions.swift:7:11: Use of unresolved identifier 'safeAreaInsets'`

How can I fix this?
Thanks.

```
Project Deployment Target: 9.3
Operating System: macOS Sierra 10.12.6 (16G29)
Xcode: 8.3.2 (8E2002)
```

**Comment by jondwillis** [comment]
You need to compile with Xcode 9.x

**Comment by onmyway133** [comment]
@omidgolparvar Hi, can you try suggestion from @jondwillis ?

**Comment by omidgolparvar** [comment]
@onmyway133 Hi, I found out that using `Whisper (5.0.0)` in my project will temporary solve my problem.

**Comment by onmyway133** [comment]
@omidgolparvar OK, I will close this issue for now 😉
