### ISSUE TITLE
Xcode 9 Runtime issue

### ISSUE THREAD

**Issue by motapuma** [hyperoslo/Whisper#194]
With the Xcode 9 there is a "RunTIme Issue:

![screen shot 2017-11-13 at 11 16 48 pm](https://user-images.githubusercontent.com/4665501/32764014-ec3691e4-c8c8-11e7-983d-1e592f0cff46.png)
"

**Comment by onmyway133** [comment]
@motapuma Hi, can you check that you don't use Whisper from background thread?

**Comment by motapuma** [comment]
Yes i did, therefore now i am  sure i am not using Whisper from background. I have done a new project i have surrounded every code that involves whisper with 
`DispatchQueue.main.sync {}`

Aren't you experiencing the same with Xcode 9 ???? (Because this warning were not present with Xcode 8.0)

But the code  in the next image fix the "Run time issue"

![screen shot 2017-11-28 at 2 22 31 am](https://user-images.githubusercontent.com/4665501/33309252-112f5c04-d3e3-11e7-842e-46c66a6ea745.png)

If you think it is a good idea ill do the pull request...

**Comment by albertomota-codes** [comment]
@3lvis  just like that?

**Comment by 3lvis** [comment]
Hi @albertomota-codes, 

Haven't been able to reproduce the issue, if this is still a case for you and can help me reproduce it I'll be happy to revisit it :)
