### ISSUE TITLE
iPhone X Landscape: Whisper uses wrong offset

### ISSUE THREAD

**Issue by Laptopmini** [hyperoslo/Whisper#197]
- iPhone X
- iOS 11.1
- Xcode 9.1
- Whisper 6.0.2

![](https://i.imgur.com/Kmw7atN.png)

```swift
let whisperMessage = Whisper.Message(title: message, textColor: .white, backgroundColor: color)
Whisper.show(whisper: whisperMessage, to: navigationController)
```

**Comment by buscarini** [comment]
I'm seeing the same thing on iPad landscape

**Comment by pchmelar** [comment]
+1

**Comment by ivanorotondo** [comment]
I had a similar problem, this code could maybe help someone in the future.

My problem was that the whisper view origin.y was calculated wrong when in landscape (the navigation bar height gets smaller) and therefor there was an empty space between whisper and navigationbar.

I solved changing the code in **WhisperFactory.swift**:

```
func navigationController(_ navigationController: UINavigationController, willShow viewController: UIViewController, animated: Bool) {
    ...

    
    if UIDevice.current.orientation.isLandscape {
        maximumY = 32
    } else {
        maximumY = 44
    }

    whisperView.frame.origin.y = maximumY
    ...
}
```
