### ISSUE TITLE
Design awesome icon

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Whisper#2]

**Comment by vadymmarkov** [comment]
@RamonGilabert I've seen some cool icon on your screen, where is it? :smiley_cat:

**Comment by RamonGilabert** [comment]
Dude it's hard as balls. And @zenangst thinks in changing the name...

R.I.P. Whisper.

**Comment by vadymmarkov** [comment]
:scream: Why are you doing this @zenangst I can't imagine this world without Whisper.

**Comment by zenangst** [comment]
Well, in my opinion, Whisper doesn't work anymore because its just one of the methods that you use inside. But that is just my opinion :sunglasses: 

![the-big-lebowski-reunion-animated-gifs-15](https://cloud.githubusercontent.com/assets/57446/11420766/92a6a96c-9430-11e5-849c-0d2734c1f288.gif)

**Comment by RamonGilabert** [comment]
:scream:?

**Comment by RamonGilabert** [comment]
What about Sounds?

**Comment by vadymmarkov** [comment]
Do we have sounds?
