### ISSUE TITLE
Fix iPhone X Shout

### ISSUE THREAD

**Issue by aturri** [hyperoslo/Whisper#200]
- iPhone X
- iOS 11.2
- Xcode 9.2
- Whisper 6.0.2
<img width="453" alt="schermata 2018-02-27 alle 22 49 05" src="https://user-images.githubusercontent.com/6987093/36756928-b6d367fc-1c10-11e8-9c3b-97432fc09f34.png">
`let announcement = Announcement(title: "Your title", subtitle: "Your subtitle")
  Whisper.show(shout: announcement, to: rootViewController, completion: {
                print("The shout was silent.")
   })`

**Comment by csr** [comment]
+10000000000000, very ugly
![simulator screen shot - iphone x - 2018-09-03 at 14 57 05](https://user-images.githubusercontent.com/10504710/44988104-d42e8900-af89-11e8-96db-b1b0bdb8d10d.png)
