### ISSUE TITLE
View slides up

### ISSUE THREAD

**Issue by artuan** [hyperoslo/Whisper#206]
After few times of showing the whisper going to the next page on demo, the view controller slides up.. 
![simulator screen shot - iphone 8 plus - 2018-08-08 at 22 21 04](https://user-images.githubusercontent.com/14091591/43862253-742ae7ae-9b59-11e8-8045-d6e2ac92275c.png)

**Comment by majid701** [comment]
I have noticed it as well! 
if a view is showing a whisper and you move to another view controller containing a collection view or table view when the whisper dismisses it slides up the top of the collection view or table view as well making invisible the first element of the table view! 
Any fixes?
