### ISSUE TITLE
Swift 4.2 support

### ISSUE THREAD

**Issue by iMac0de** [hyperoslo/Whisper#207]
Hello !

Since Xcode 10 and Swift 4.2 has been released, the framework doesn't compile anymore.

Regards,

iMac0de

**Comment by gorbat-o** [comment]
Hey,

I feel like this repo is not maintained anymore :(
By waiting the new release, I am doing this:

```
pod 'Whisper', :git => 'git@github.com:freeubi/Whisper.git', :branch => 'swift-4.2-support'
```

**Comment by jfahrenkrug** [comment]
For me the best solution was to switch to using NotificationBannerSwift: https://github.com/Daltron/NotificationBanner

**Comment by uypanha** [comment]
@jfahrenkrug Thanks, I've been seeking for alternative framework since this one is longer maintain... 😄
