### ISSUE TITLE
Whisper effect it's superview when it's called to show in viewDidLoad or viewDidAppear

### ISSUE THREAD

**Issue by haithngnbak** [hyperoslo/Whisper#22]
Hello,
Merry X-Mas ! 

I have a problem when I try to show Whisper at the functions viewDidLoad or viewDidAppear the tableview add strange space at it's top, please take a look in to the attached photo
![screen shot 2015-12-25 at 12 42 48 am](https://cloud.githubusercontent.com/assets/1132303/11996910/80d8d5da-aaa0-11e5-9dad-6098aa97aaf3.png)

if I show Whisper by using the button it work perfect.

You could found this bug in my demo project : https://github.com/0x686169/NiceWhisper

Hope you fix this soon as soon.

Thank you very much,

**Comment by arthur-here** [comment]
This problem is that `moveControllerViews(down:)` is called twice:
1. Firstly from `viewDidAppear`/`viewDidLoad` stack when Whisper is shown
2. And second time in `UINavigationControllerDelegate`'s method - `navigationController(navigationController: UINavigationController, willShowViewController viewController: UIViewController, animated: Bool)`

**Comment by haithngnbak** [comment]
@burntheroad,
Sorry where is moveControllerViews ? I'm still not get your idea :D
the  function self.show() is just called one time at viewDidAppear, Can you set debug break point at that line.
And can you fix this issue in my demo preject ?

Thanks,

**Comment by arthur-here** [comment]
@0x686169,
Sorry for unclear comment. I talk about issue in Whisper's source, which I don't know how to fix yet. 😔

**Comment by RamonGilabert** [comment]
Looking at it now! Thank you for reporting @0x686169 and thank you @burntheroad :)

**Comment by RamonGilabert** [comment]
Fixed in #33, it's like a small patch, but it's basically an if that tells if the view is down already and the whisper is being shown. If that's the case, it won't do anything.

Try after it's merged and keep us posted! :)

**Comment by haithngnbak** [comment]
Are you still working on this ?

**Comment by haithngnbak** [comment]
still doesn't work

**Comment by zenangst** [comment]
@0x686169 we will have another look :sunglasses:

**Comment by RamonGilabert** [comment]
We didn't update CocoaPods yet though @0x686169, that means that to try it out you need to point to master in your podfile.

**Comment by haithngnbak** [comment]
hi @RamonGilabert ,
I'm using Carthage :)

**Comment by haithngnbak** [comment]
Wow,
Today I checkout the latest code and I don't see this bug :(.

Thanks agains,
