### ISSUE TITLE
How to change Shout color

### ISSUE THREAD

**Issue by seapy** [hyperoslo/Whisper#26]
Shout color change is possible?

**Comment by zenangst** [comment]
Hey @seapy, `Shout`'s use the `ColorList` for configuration. 
`ColorList.Shout.background` is a static variable so you are able to configure it to what ever color you want. It defaults to `UIColor.whiteColor()`.

```
ColorList.Shout.backgroundColor = UIColor.greenColor()
```

Let us know how it goes and thanks for using `Whisper` :sunglasses:

**Comment by seapy** [comment]
@zenangst i try under the code in demo, but color not expected color

``` swift
let announcement = Announcement(title: "Ramon Gilabert", subtitle: "Vadym Markov just commented your post", image: UIImage(named: "avatar"))
ColorList.Shout.background = UIColor.redColor()
ColorList.Shout.title = UIColor.whiteColor()
Shout(announcement, to: self, completion: {
    print("The shout was silent.")
})
```

result, not red background color and not white text color.

![simulator screen shot 2015 12 31 1 26 48](https://cloud.githubusercontent.com/assets/421486/12053545/98896dd6-af5d-11e5-9b76-313d7291ff57.png)

**Comment by RamonGilabert** [comment]
Hey @seapy! It is possible, there was a legacy view in the Shout to make some sort of blur notification but we weren't using anymore, pretty much, now you can change everything.

There was also a mistake in the labels fixed in #32!

**Comment by zenangst** [comment]
Fixed by https://github.com/hyperoslo/Whisper/issues/32

**Comment by seapy** [comment]
Test Demo app and it works. :+1: 
and need update cocoapod
