### ISSUE TITLE
How to use this framework with objective-c?

### ISSUE THREAD

**Issue by afiq90** [hyperoslo/Whisper#28]
How to use this framework with objective-c?

**Comment by RamonGilabert** [comment]
Hey @afiq90! Well this framework wasn't thought for Objective C to be honest, and it's been a while since I do a project with it, so I don't know how that stuff work anymore to do a Swift - Objective C podfile. Sorry about that.

**Comment by bjones2015** [comment]
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html 

The "Importing Swift into Objective-C" section gives instructions on how to do this.

**Comment by RamonGilabert** [comment]
Thank's @bjones2015.

**Comment by brianinator** [comment]
+1 I really like the concept and would like to use in an obj-c project.

**Comment by bcbroom** [comment]
As is, it will not run from Obj-C. Obj-C cannot use Swift structs or functions outside of a class declaration. To use this as is, you need to add a "bridge" layer by adding a swift class, reachable from Obj-C, that passes the call on to the swift version. I did something like this

```
// WhisperBridge.swift
import Foundation
import Whisper

@objc public class WhisperBridge: NSObject {

  static public func whisper(text: String, backgroundColor: UIColor, toNavigationController: UINavigationController, silenceAfter: NSTimeInterval) {
    let message = Message(title: text, color: backgroundColor)
    Whisper(message, to: toNavigationController)

    if silenceAfter > 0.1 {
      Silent(toNavigationController, after: silenceAfter)
    }
  }
}
```

Then in ViewController.m

```
#import "ViewController.h"
#import "WhisperTest-swift.h"

@implementation ViewController
- (void)viewDidLoad {
  [super viewDidLoad];

  [WhisperBridge whisper:@"Message to Send!" backgroundColor:[UIColor orangeColor] toNavigationController:self.navigationController silenceAfter:3.0];
}
@end
```

**Comment by brianinator** [comment]
@bcbroom What is #import "WhisperTest-swift.h" from? Can you give more info on this class? I am trying get the WhisperBridge swift file to be recognized in obj-c class. I get file not found when I use #import "WhisperBridge-Swift.h" in obj-c class.

**Comment by bcbroom** [comment]
Its a generated header file - the pattern is "TargetName"-Swift.h. My project (and default target name) was "WhisperTest". There is only one for the whole target, not one for each Swift file.

**Comment by brianinator** [comment]
@bcbroom Oh I see. Thanks and I changed it and it worked. :+1:

**Comment by zenangst** [comment]
@bcbroom that is amazing, thanks for answering this issue and finding a feasible solution for Objective-C support; mind adding it to the `README`? =)

**Comment by RamonGilabert** [comment]
So :top: @bcbroom! :)
