### ISSUE TITLE
CONTRIBUTING.md references ImagePicker not Whisper documentation

### ISSUE THREAD

**Issue by brianinator** [hyperoslo/Whisper#35]

**Comment by zenangst** [comment]
![giphy-72](https://cloud.githubusercontent.com/assets/57446/12152802/c563e6d4-b4b6-11e5-8357-902ed3ea8ec7.gif)

@devbriguy Just kidding, thanks for letting us know :grin:

**Comment by RamonGilabert** [comment]
Fixed. I did it through the Github editor, so didn't quite made a PR. :)

This was a big fail. :smile:
