### ISSUE TITLE
Feature: add an activity notification, with progress bar

### ISSUE THREAD

**Issue by oferRounds** [hyperoslo/Whisper#50]
Facebook uses a nice in-app banner when the user taps "Post". The user see a progress bar indicating the posting process, while at end, signalling it's done.

Would be great if such one will be added to Whisper.

**Comment by zenangst** [comment]
Oh that sounds nifty, maybe we could implement another type of message that has progression in it. Really great suggestion!

**Comment by oferRounds** [comment]
Yay! Glad you liked it! :-)

**Comment by zenangst** [comment]
We need a good name for it that fits in with the rest 🤔

**Comment by oferRounds** [comment]
How about just Task? (I'm not a native english speaker, so I'm sure there's a cooler one :) )

**Comment by jyounus** [comment]
+1 for this request, this is exactly what I need in my project!

How about calling it "Mission". :D

**Comment by oferRounds** [comment]
Mission sounds good to me :)

**Comment by aashishdhawan** [comment]
Yeah...Mission!!!

**Comment by oferRounds** [comment]
Hey 
Just wanted to find out if perhaps anyone is planing to work on this feature
If this is on anyones plans it would be great to know!

**Comment by onmyway133** [comment]
@oferRounds Hi, it is in my plan. I'd prefer it to be in another repo. @zenangst 😬

**Comment by oferRounds** [comment]
Sounds good - thanks for the update!

**Comment by ndmeiri** [comment]
@jyounus I like the way Mission sounds, but I don't know if it matches Whisper, Shout, and Whistle. I'm trying to think of an alternative to Mission, but I haven't come up with anything yet.

@onmyway133 What do you mean by you'd prefer the feature to be in another repo? Do you think this feature is outside the scope of Whisper?

**Comment by tiferrei** [comment]
@oferRounds I got it! **Murmur**!! _A low, continuous background noise_, matches perfectly!

**Comment by oferRounds** [comment]
@tiferrei - Yay, way to go! Sounds perfect!
