### ISSUE TITLE
Whistle's content is cropped

### ISSUE THREAD

**Issue by acadet** [hyperoslo/Whisper#51]
[From what I have seen so far](https://github.com/hyperoslo/Whisper/blob/master/Source/WhistleFactory.swift#L12), the height of any whistle/murmur is fixed and not dynamic. Then, if its content is too long, it is simply cropped/hidden.

Can we update this?

Also, would it be possible to add a parameter for inner margins? I can help if needed.

**Comment by zenangst** [comment]
Closing this one now :sunglasses:
