### ISSUE TITLE
Support Buttons

### ISSUE THREAD

**Issue by mRs-** [hyperoslo/Whisper#52]
In the current implementation **Whisper** has no intention to use buttons in the whisper. Is it possible to add buttons with different callbacks to manage this?

**Comment by RamonGilabert** [comment]
Hey @mRs-! Are we talking about buttons in just Whisper, or also in Shouts? This could be a good enhancement.

**Comment by mRs-** [comment]
Both!

Von meinem iPhone gesendet

**Comment by RamonGilabert** [comment]
Can you tell me a use case for that? :)

**Comment by mRs-** [comment]
Inform the User about an Update of the current screen. But you don't want to refresh it directly because the user is interacting with the current screen at the moment and an update without asking would be very rude. 

Von meinem iPhone gesendet

**Comment by mRs-** [comment]
Any updates?

**Comment by BilalReffas** [comment]
I think this would be a great feature as well !
