### ISSUE TITLE
Bug: Incorrect position of Whistle. 

### ISSUE THREAD

**Issue by aashishdhawan** [hyperoslo/Whisper#58]
I was playing with it and after some random rotations this happened. Looks like a bug to me. The latest commit on which this happened is dc4fe41.
![simulator screen shot 30-jan-2016 9 49 43 pm](https://cloud.githubusercontent.com/assets/1090001/12696903/d37086fe-c79b-11e5-8a27-6c66bf706bd9.png)

**Comment by aashishdhawan** [comment]
![simulator screen shot 30-jan-2016 10 08 17 pm](https://cloud.githubusercontent.com/assets/1090001/12696994/1b19a4ca-c79e-11e5-801b-4c5a06706649.png)

**Comment by minuscorp** [comment]
I'm suffering this bug too, is someone on this or I should try to fix it?

**Comment by minuscorp** [comment]
It seems like adding:

``` swift
whistleWindow = UIWindow()
setupWindow()
```

to the `public func setupFrames()` solves the issue.

**Comment by Lwdthe1** [comment]
Is this resolved?

**Comment by vadymmarkov** [comment]
Seems like this bug is fixed.
