### ISSUE TITLE
Ability do display subtitle on multiple lines

### ISSUE THREAD

**Issue by thierrybucco** [hyperoslo/Whisper#65]
I would like to display subtitle on multiple lines.
Like in this fork: [https://github.com/djz-code/Whisper/commit/0e967280a05364a6ec05b665056067772a15c308](https://github.com/djz-code/Whisper/commit/0e967280a05364a6ec05b665056067772a15c308)

**Comment by LucidityDesign** [comment]
Therefore I made a pull request: #61

**Comment by RamonGilabert** [comment]
We have support for 2 lines now! :)
