### ISSUE TITLE
Feature: Handle a queue of notifications

### ISSUE THREAD

**Issue by clemkoa** [hyperoslo/Whisper#66]
Right now if you trigger two Shouts, only the last one will be displayed. The second one should wait until the first one has been removed, so no notification is hidden.

This could be done with an array of notifications, and a callback everytime a notification is terminated: if the array is not empty then we display the next one.

Not sure if this feature is part of your roadmap, but I thought i would be a nice to have

**Comment by RamonGilabert** [comment]
Hey @clemkoa! Thank's for commenting, this would be, indeed, a great addition into Whisper.

@hyperoslo/malibu.

**Comment by clemkoa** [comment]
I opened a [Pull Request](https://github.com/hyperoslo/Whisper/pull/71) for this feature.

**Comment by kbduvall** [comment]
You could use the existing completion blocks to send queues of messages.
This is untested, but you could try something like this:

``` Swift
class MyShout {
    let parent: UINavigationController
    var messages: [String]

    init(parent: UINavigationController, messages: [String]) {
        self.parent = parent
        self.messages = messages
    }
    func sendShout() {
        if let msg = messages.popLast() {
            let announce = Announcement(title: "Queued Shouts", subtitle: msg)
            Shout(announce, to: parent) {
                if self.messages.count > 0 {
                    self.sendShout()
                }
            }
        }
    }
}

let messages = ["message1", "message2", "message3"]
MyShout(self, messages: messages).sendShout()
```

**Comment by clemkoa** [comment]
@hyperoslo any feedback on this ?
