### ISSUE TITLE
Whistle restart application without crashing

### ISSUE THREAD

**Issue by VivienGiraud** [hyperoslo/Whisper#68]
Hi,
If I try to call a Murmur my application restart to the Initial View Controller.

```
var murmur = Murmur(title: "Can you retry please?")
Whistle(murmur) //Restart if this is not commented
```

Same behavior with iPhone or simulator. Only tested with latest SDK iOS 9.2.0.
Any idea?

**Comment by VivienGiraud** [comment]
Wherever I put this it print the Whistle then it restart the app to the Initial View Controller.
`Whistle(Murmur(title: " was successfully pushed!"))`
I use pod version 2.1.
Any idea?

**Comment by truongvinht** [comment]
interesting... it still occurs in Whisper 3.1.1

Any fix coming?

**Comment by VivienGiraud** [comment]
@truongvinht You have the same behaviour? 
That's really strange that nobody else complains, such a simple code sample can't work, weird.

**Comment by onmyway133** [comment]
@Miasma87 Hi, have you run the Whisper demo app? Is showing whistle a problem with you there?

``` swift
let murmur = Murmur(title: "This is a small whistle...", backgroundColor: UIColor(red: 0.975, green: 0.975, blue: 0.975, alpha: 1))
show(whistle: murmur)
```

What do you mean by `restart to the Initial View Controller`? Perhaps you could share some code so we can have further investigation on it

**Comment by RamonGilabert** [comment]
Hey @Miasma87, tried to run the demo and it worked fine. Also tried to run it in one of the apps we are doing. It works too.

I find this specially weird. Does this happen in all the cases?

**Comment by RamonGilabert** [comment]
Tried in the Swift 3 branch, everything works. Closing this for now. Feel free to reopen.

**Comment by TomasPangzi** [comment]
when Murmur is showing, I present another view controller or dismiss current view controller, application will crash without error
