### ISSUE TITLE
Problem with TableView Insets

### ISSUE THREAD

**Issue by PabloLV** [hyperoslo/Whisper#70]
Hi! 
I have two TableViewControllers as you can see in the video I've attached here.
In the 2nd one I show a permanent Whisper notification (the only thing I've changed is the WhisperView height to 38). When the user press back, on viewWillDisappear() I invoke Silent(navigationController!) and the insets for the first TableViewControllers breaks. It returns top = -38 instead of top = 0.0, as my navigationBar is opaque, not transparent.
The second time I do it, as you can see in the video, the insets becomes worst, because this time it returns top = -76, so 38 x 2. And it goes on and on.
I have tried to solve this but couldn't exactly found the right line to modified in the pod.
Hope you can help me!
Thank you very much!
Pablo
![movie](https://cloud.githubusercontent.com/assets/14890607/13757610/17398324-ea04-11e5-8dd5-45f923c2b2cd.gif)

**Comment by RamonGilabert** [comment]
Hey @PabloLV. Thank's for reporting.

1st. Nice design, love the font and how Whisper fits inside.
2nd. I'll be working on Whisper this Friday since we have to do a release version for it. I guess the problem is that you dismiss the view right exactly when you go back to your controller. I know that shouldn't be a concern of yours, but a workaround could be to set the contentInset of your controller the one it should be in `viewWillAppear`, or `viewDidAppear`. I'll keep you posted this Friday.

**Comment by PabloLV** [comment]
@RamonGilabert thanks for your quick answer! I tried setting the contentInset on viewwillAppear with no success, a blank space at top of the table view was the only thing I got. 
Tonight I will spend some more time on this and if I found a workaround I will let you know. 
But for sure I'm updating Whisper on your next release. 
Thanks!!

**Comment by PabloLV** [comment]
@RamonGilabert Update!
I'm no expert regarding contentInsets, offsets, sizes, and on and on, but after some work a I found an awful solution, but it works at least for now! 

On viewWillDisappear method from the first TVC, I save the contentOffset when it moves to another view, and if it comes back, on the viewWillAppear method I replace the current contentOffset with the one saved before:

`override func viewWillAppear(animated: Bool)
    {
        super.viewWillAppear(animated)

```
    if let contentOffset = contentOffset
    {
        tableView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0)
        tableView.contentOffset = contentOffset
    }
}

override func viewWillDisappear(animated: Bool)
{
    contentOffset = tableView.contentOffset
}`
```

Hope it helps to solve this bug, looking for to hearing about that Whisper update, great pod!

**Comment by amanbolat** [comment]
@PabloLV I faced the same problem and your solution helped me. But i only added 
`tableView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0)
`
into `viewWillAppear`, so when i come back from another View controller inset will be correct.

**Comment by Kalzem** [comment]
I confirm this bug with UICollectionView too.
I have a UIViewController with a horizontal collectionView inside. Sometimes I call Whisper (with auto hide) and the collectionView is being pushed down by the height of the Whisper then get's back to its original position.

A reset of the contentOffset/Inset doesn't change anything as I need to call them during animations of the Whisper (in and out).

Also, I have `automaticallyAdjustsScrollViewInsets` set to false, it doesn't help.

**Comment by Kalzem** [comment]
I just found out you can do this:

`Config.modifyInset = false` in viewDidLoad

**Comment by StarWars** [comment]
This is still happening. I have a UITableView with search bar, and calling Whisper (with auto hide), causes huge offset problems. The searchbar hides below navigation bar when it loses focus, on the other hand, when it is focused, the top offset is improper.

**Comment by benguild** [comment]
It seems like the "for sure" solution is to not risk any funky behavior, and always use:
```
Config.modifyInset = false
```

**Comment by bibekdari** [comment]
@BabyAzerty worked perfectly.

**Comment by kerrmarin** [comment]
This is still happening, any update for a solution to this?

**Comment by bibekdari** [comment]
@kerrmarin put that `Config.modifyInset = false` in app delegate on didFinishLaunchingWithOptions.

**Comment by kerrmarin** [comment]
Yeah, I see that fixes it, I just think it would be nice not to have to do that. Thanks
