### ISSUE TITLE
Whisper not building after Xcode update 7.3

### ISSUE THREAD

**Issue by vdupuis** [hyperoslo/Whisper#74]
/Pods/Whisper/Source/WhisperFactory.swift:289:72: Value of type 'Index' (aka 'Int') has no member 'value'

Xcode Version 7.3 (7D175)

**Comment by onmyway133** [comment]
@judyspikes how about a PR for that? :wink:

**Comment by clemkoa** [comment]
This has been fixed in version 2.1. You need to update your podfile with

```
  pod 'Whisper', '~> 2.1'
```

Then run `pod install`, and the problem should be fixed

**Comment by RamonGilabert** [comment]
Thanks @clemkoa! Closing this.
