### ISSUE TITLE
modifyInset issue

### ISSUE THREAD

**Issue by LiMaoAtCD** [hyperoslo/Whisper#79]
I use Whisper in my navigationController with a tableviewController ,but I use a pull to refresh to my tableViewController. when the Whisper shows ,the tableView Inset changed,which makes my tableview inset changed.I changed the Config.swift property modifyInset to False ,that is fine.so I'm weird if is possible to public this property

**Comment by jaffacake** [comment]
Can I also request this, we have this issue throughout our app. The biggest one is that we use whisper to show a notification after a user click add to basket. We hide it after 3 seconds, but if you press the button really fast it starts deleting height from the view.

I tried @liamscofield's fix and it fixed it for me. Is there any other solution? Or can this be implemented?

**Comment by jaffacake** [comment]
Actually, on testing it a second time, doing `Whisper.Config.modifyInset = false` in my app delegate fixes this. Is this the correct way of changing it?

**Comment by anirudhamahale** [comment]
Doing `Whisper.Config.modifyInset = false` helped me but the working has changed. The UITableView's top `contentInset.top` isn't changing.

**Comment by RamonGilabert** [comment]
We'll close this and put it in the same pile as #70, since basically is the same issue. Thanks for reporting! :)
