### ISSUE TITLE
Action on Notification tap

### ISSUE THREAD

**Issue by regeint** [hyperoslo/Whisper#82]
Hi,

This library is awesome but I need one feature in it which I think is essential for any notification.
I need to implement action when user taps on shout announcement. 
I did not find it anywhere. If it is already implemented, please mention and close this issue.

Thanks!

**Comment by onmyway133** [comment]
@regeint Hi,

`Announcement` has `action` https://github.com/hyperoslo/Whisper/blob/master/Source/Message.swift#L24 that is called when you tap onto it https://github.com/hyperoslo/Whisper/blob/master/Source/ShoutFactory.swift#L218, it is achieved through `handleTapGestureRecognizer`

**Comment by regeint** [comment]
Thanks @onmyway133!
I was searching this in readme. I think someone should update readme as well. :)

**Comment by alberttai1** [comment]
Is there an example of this? It's a little confusing how to implement since it is a (() -> Void)?. I'm not suer how to even call my function properly

**Comment by ahaverty** [comment]
@alberttai1 

Try:
```swift
Announcement(title: "title", subtitle: "subTitle", duration: 5, action: {
    print("action clicked!")
})
````
