### ISSUE TITLE
Whisper doesn't work in custom Formsheets

### ISSUE THREAD

**Issue by ghost** [hyperoslo/Whisper#85]
Showing a whisper in a UINavigationController in a Form Sheet results in an unreadable message

**Comment by RamonGilabert** [comment]
Could you post a screenshot of what you mean? 😊

**Comment by dungi** [comment]
Have the same issue - the whisper is always the size of the screen - not from foresheet

**Comment by jmjordan** [comment]
WhisperView does not account for the navigationController's width. I have a fix that I will try to create a PR for.
