### ISSUE TITLE
How to make text in a Whisper wrap?

### ISSUE THREAD

**Issue by akhilm3** [hyperoslo/Whisper#86]
Title explains all

**Comment by everhardt** [comment]
+1

**Comment by johnkueh** [comment]
+1

**Comment by tkohout** [comment]
If you need wrapping for two lines (as it is in system notifications) it was added in https://github.com/hyperoslo/Whisper/commit/df4be98016b01241123f0397728435a35e6a733f . It is just not in release yet. For more advanced 'unveiling' of extra text I have submitted new pull request https://github.com/hyperoslo/Whisper/pull/108

**Comment by onmyway133** [comment]
@tkohout thanks for your answer. We can now access this via release 3.1.0
