### ISSUE TITLE
Shouts on UIWindowLevelStatusBar or UIWindowLevelAlert

### ISSUE THREAD

**Issue by harri121** [hyperoslo/Whisper#94]
Is it possible to have Shouts on UIWindowLevelStatusBar or UIWindowLevelAlert?

**Comment by RamonGilabert** [comment]
Not from now, since it just gets displayed in the controller. But maybe it could be interesting to add that, why would you want it?

Closing the issue for now, since sadly at the moment I don't think the core team will spend time on it, as we have Whistle to perform messages in a window level.
